version: '3.9'

services:
  postgress:
    image: postgres:16.2-alpine3.19
    ports:
      - 5432:5432
    volumes:
      - ~/work/apps/databases/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=weather_and_traffic